import { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: 1,
    title: "Morning Yoga Session",
    description: "Start your day with peaceful yoga in the park! 🧘‍♀️ All levels welcome",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=800&fit=crop",
    organizer: { name: "Sarah Johnson", avatar: "👩‍🦰" },
    time: "8:00 AM - 9:30 AM",
    date: "Today",
    location: "Central Park",
    latitude: 40.785091,
    longitude: -73.968285,
    attendees: 12,
    maxAttendees: 15,
    tags: ["Health", "Outdoor", "Beginner"],
    cost: 0,
    requiresApproval: false,
    isFavorite: false,
    isCommitted: false,
    commitmentStatus: null
  },
  {
    id: 2,
    title: "Photography Walk",
    description: "Capture the city's beauty with fellow photographers 📸",
    imageUrl: "https://images.unsplash.com/photo-1434394354979-a235cd36269d?w=400&h=800&fit=crop",
    organizer: { name: "Mike Chen", avatar: "👨‍💼" },
    time: "2:00 PM - 4:00 PM",
    date: "Tomorrow",
    location: "Brooklyn Bridge",
    latitude: 40.706086,
    longitude: -73.996864,
    attendees: 8,
    maxAttendees: 12,
    tags: ["Photography", "Walking", "Art"],
    cost: 25,
    requiresApproval: false,
    isFavorite: true,
    isCommitted: false,
    commitmentStatus: null
  },
  {
    id: 3,
    title: "Book Club Meeting",
    description: "Join our cozy book discussion! This month: The Great Gatsby 📚",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=800&fit=crop",
    organizer: { name: "Emma Wilson", avatar: "👩‍🎓" },
    time: "7:00 PM - 8:30 PM",
    date: "Friday",
    location: "Local Library",
    latitude: 40.753182,
    longitude: -73.982253,
    attendees: 6,
    maxAttendees: 10,
    tags: ["Reading", "Discussion", "Indoor"],
    cost: 0,
    requiresApproval: true,
    isFavorite: false,
    isCommitted: true,
    commitmentStatus: 'pending'
  },
  {
    id: 4,
    title: "Premium Cooking Class",
    description: "Learn to cook authentic Italian pasta from a master chef! 🍝👨‍🍳",
    imageUrl: "https://images.unsplash.com/photo-1656711776904-993edf967bbf?w=400&h=800&fit=crop",
    organizer: { name: "Chef Antonio", avatar: "👨‍🍳" },
    time: "6:00 PM - 8:00 PM",
    date: "Saturday",
    location: "Culinary School",
    latitude: 40.748817,
    longitude: -73.985428,
    attendees: 10,
    maxAttendees: 10,
    tags: ["Cooking", "Premium", "Learning"],
    cost: 75,
    requiresApproval: false,
    isFavorite: false,
    isCommitted: false,
    commitmentStatus: null
  },
  {
    id: 5,
    title: "Community Garden Planting",
    description: "Help plant flowers and vegetables in our community garden! 🌱 Free event",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=800&fit=crop",
    organizer: { name: "Jessica Green", avatar: "👩‍🌾" },
    time: "9:00 AM - 12:00 PM",
    date: "Sunday",
    location: "Community Garden Center",
    latitude: 40.730610,
    longitude: -73.935242,
    attendees: 20,
    maxAttendees: 20,
    tags: ["Gardening", "Community", "Free"],
    cost: 0,
    requiresApproval: false,
    isFavorite: false,
    isCommitted: false,
    commitmentStatus: null
  }
];
